### ISSUE TITLE
Readability of README

### ISSUE THREAD

**Issue by estenhl** [gislebh/Return_to_Work_after_Stroke#2]
The README-file is currently not that readable in its rendered format, although the underlying text file looks structured. I would revise it and ensure that e.g. the line breaks appear as desired, see the below guide for inspiration on syntax.

https://github.com/mattcone/markdown-guide/blob/master/_basic-syntax/line-breaks.md

**Comment by gislebh** [comment]
Good point, thanks. Now fixed!
